LOAD DATA INFILE '/Users/hitesh/Downloads/test_budy/sqlangchain/NY-House-Dataset.csv'
INTO TABLE Broker
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@broker_title, TYPE, PRICE, BEDS, BATH, PROPERTYSQFT, @address, STATE, MAIN_ADDRESS, ADMINISTRATIVE_AREA_LEVEL_2, LOCALITY, SUBLOCALITY, STREET_NAME, LONG_NAME, FORMATTED_ADDRESS, LATITUDE, LONGITUDE)
SET BROKERTITLE = SUBSTRING_INDEX(@broker_title, ' - ', 1);

LOAD DATA INFILE '/Users/hitesh/Downloads/test_budy/sqlangchain/NY-House-Dataset.csv'
INTO TABLE Address
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@broker_title, TYPE, PRICE, BEDS, BATH, PROPERTYSQFT, @address, STATE, MAIN_ADDRESS, ADMINISTRATIVE_AREA_LEVEL_2, LOCALITY, SUBLOCALITY, STREET_NAME, LONG_NAME, FORMATTED_ADDRESS, LATITUDE, LONGITUDE)
SET ADDRESS = @address;

LOAD DATA INFILE '/Users/hitesh/Downloads/test_budy/sqlangchain/NY-House-Dataset.csv'
INTO TABLE Property
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@broker_title, TYPE, PRICE, BEDS, BATH, PROPERTYSQFT, @address, STATE, MAIN_ADDRESS, ADMINISTRATIVE_AREA_LEVEL_2, LOCALITY, SUBLOCALITY, STREET_NAME, LONG_NAME, FORMATTED_ADDRESS, LATITUDE, LONGITUDE)
SET BROKERTITLE = SUBSTRING_INDEX(@broker_title, ' - ', 1),
    ADDRESS_ID = (SELECT ADDRESS_ID FROM Address WHERE ADDRESS = @address);
